definitions:
  model.Movie:
    properties:
      genres:
        items:
          properties:
            id:
              type: integer
            name:
              type: string
          type: object
        type: array
      id:
        type: integer
      overview:
        type: string
      poster_path:
        type: string
      release_date:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /movie/{id}:
    get:
      description: Fetch detailed information for a movie by its TMDB ID
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Movie'
        "500":
          description: Failed to fetch movie details
          schema:
            type: string
      summary: Get movie details
      tags:
      - Movies
  /trending/movie/{day_or_week}:
    get:
      description: Fetch trending movies for a specified timeframe ("day" or "week")
      parameters:
      - description: Timeframe
        enum:
        - day
        - week
        in: path
        name: day_or_week
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Movie'
            type: array
        "500":
          description: Failed to fetch trending movies
          schema:
            type: string
      summary: Get trending movies
      tags:
      - Movies
swagger: "2.0"
